/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as PublicTestIndexImport } from './routes/_public/test/index'
import { Route as PublicLoginIndexImport } from './routes/_public/login/index'
import { Route as PublicForgotPassIndexImport } from './routes/_public/forgot-pass/index'
import { Route as AuthUsersIndexImport } from './routes/_auth/users/index'
import { Route as AuthSubmitlabIndexImport } from './routes/_auth/submitlab/index'
import { Route as AuthStudentdashboardIndexImport } from './routes/_auth/studentdashboard/index'
import { Route as AuthStudentManageIndexImport } from './routes/_auth/student-manage/index'
import { Route as AuthMysubmitIndexImport } from './routes/_auth/mysubmit/index'
import { Route as AuthHomeIndexImport } from './routes/_auth/home/index'
import { Route as AuthClassManageIndexImport } from './routes/_auth/class-manage/index'
import { Route as AuthAssignmentlistIndexImport } from './routes/_auth/assignmentlist/index'
import { Route as AuthAssignmentManageIndexImport } from './routes/_auth/assignment-manage/index'
import { Route as AuthAboutIndexImport } from './routes/_auth/about/index'

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PublicTestIndexRoute = PublicTestIndexImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => PublicRoute,
} as any)

const PublicLoginIndexRoute = PublicLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRoute,
} as any)

const PublicForgotPassIndexRoute = PublicForgotPassIndexImport.update({
  id: '/forgot-pass/',
  path: '/forgot-pass/',
  getParentRoute: () => PublicRoute,
} as any)

const AuthUsersIndexRoute = AuthUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSubmitlabIndexRoute = AuthSubmitlabIndexImport.update({
  id: '/submitlab/',
  path: '/submitlab/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthStudentdashboardIndexRoute = AuthStudentdashboardIndexImport.update({
  id: '/studentdashboard/',
  path: '/studentdashboard/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthStudentManageIndexRoute = AuthStudentManageIndexImport.update({
  id: '/student-manage/',
  path: '/student-manage/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthMysubmitIndexRoute = AuthMysubmitIndexImport.update({
  id: '/mysubmit/',
  path: '/mysubmit/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthHomeIndexRoute = AuthHomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthClassManageIndexRoute = AuthClassManageIndexImport.update({
  id: '/class-manage/',
  path: '/class-manage/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAssignmentlistIndexRoute = AuthAssignmentlistIndexImport.update({
  id: '/assignmentlist/',
  path: '/assignmentlist/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAssignmentManageIndexRoute = AuthAssignmentManageIndexImport.update({
  id: '/assignment-manage/',
  path: '/assignment-manage/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAboutIndexRoute = AuthAboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_auth/about/': {
      id: '/_auth/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthAboutIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/assignment-manage/': {
      id: '/_auth/assignment-manage/'
      path: '/assignment-manage'
      fullPath: '/assignment-manage'
      preLoaderRoute: typeof AuthAssignmentManageIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/assignmentlist/': {
      id: '/_auth/assignmentlist/'
      path: '/assignmentlist'
      fullPath: '/assignmentlist'
      preLoaderRoute: typeof AuthAssignmentlistIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/class-manage/': {
      id: '/_auth/class-manage/'
      path: '/class-manage'
      fullPath: '/class-manage'
      preLoaderRoute: typeof AuthClassManageIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/home/': {
      id: '/_auth/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthHomeIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/mysubmit/': {
      id: '/_auth/mysubmit/'
      path: '/mysubmit'
      fullPath: '/mysubmit'
      preLoaderRoute: typeof AuthMysubmitIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/student-manage/': {
      id: '/_auth/student-manage/'
      path: '/student-manage'
      fullPath: '/student-manage'
      preLoaderRoute: typeof AuthStudentManageIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/studentdashboard/': {
      id: '/_auth/studentdashboard/'
      path: '/studentdashboard'
      fullPath: '/studentdashboard'
      preLoaderRoute: typeof AuthStudentdashboardIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/submitlab/': {
      id: '/_auth/submitlab/'
      path: '/submitlab'
      fullPath: '/submitlab'
      preLoaderRoute: typeof AuthSubmitlabIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersIndexImport
      parentRoute: typeof AuthImport
    }
    '/_public/forgot-pass/': {
      id: '/_public/forgot-pass/'
      path: '/forgot-pass'
      fullPath: '/forgot-pass'
      preLoaderRoute: typeof PublicForgotPassIndexImport
      parentRoute: typeof PublicImport
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginIndexImport
      parentRoute: typeof PublicImport
    }
    '/_public/test/': {
      id: '/_public/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof PublicTestIndexImport
      parentRoute: typeof PublicImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAboutIndexRoute: typeof AuthAboutIndexRoute
  AuthAssignmentManageIndexRoute: typeof AuthAssignmentManageIndexRoute
  AuthAssignmentlistIndexRoute: typeof AuthAssignmentlistIndexRoute
  AuthClassManageIndexRoute: typeof AuthClassManageIndexRoute
  AuthHomeIndexRoute: typeof AuthHomeIndexRoute
  AuthMysubmitIndexRoute: typeof AuthMysubmitIndexRoute
  AuthStudentManageIndexRoute: typeof AuthStudentManageIndexRoute
  AuthStudentdashboardIndexRoute: typeof AuthStudentdashboardIndexRoute
  AuthSubmitlabIndexRoute: typeof AuthSubmitlabIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAboutIndexRoute: AuthAboutIndexRoute,
  AuthAssignmentManageIndexRoute: AuthAssignmentManageIndexRoute,
  AuthAssignmentlistIndexRoute: AuthAssignmentlistIndexRoute,
  AuthClassManageIndexRoute: AuthClassManageIndexRoute,
  AuthHomeIndexRoute: AuthHomeIndexRoute,
  AuthMysubmitIndexRoute: AuthMysubmitIndexRoute,
  AuthStudentManageIndexRoute: AuthStudentManageIndexRoute,
  AuthStudentdashboardIndexRoute: AuthStudentdashboardIndexRoute,
  AuthSubmitlabIndexRoute: AuthSubmitlabIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicForgotPassIndexRoute: typeof PublicForgotPassIndexRoute
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
  PublicTestIndexRoute: typeof PublicTestIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPassIndexRoute: PublicForgotPassIndexRoute,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
  PublicTestIndexRoute: PublicTestIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof PublicRouteWithChildren
  '/about': typeof AuthAboutIndexRoute
  '/assignment-manage': typeof AuthAssignmentManageIndexRoute
  '/assignmentlist': typeof AuthAssignmentlistIndexRoute
  '/class-manage': typeof AuthClassManageIndexRoute
  '/home': typeof AuthHomeIndexRoute
  '/mysubmit': typeof AuthMysubmitIndexRoute
  '/student-manage': typeof AuthStudentManageIndexRoute
  '/studentdashboard': typeof AuthStudentdashboardIndexRoute
  '/submitlab': typeof AuthSubmitlabIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/forgot-pass': typeof PublicForgotPassIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/test': typeof PublicTestIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof PublicRouteWithChildren
  '/about': typeof AuthAboutIndexRoute
  '/assignment-manage': typeof AuthAssignmentManageIndexRoute
  '/assignmentlist': typeof AuthAssignmentlistIndexRoute
  '/class-manage': typeof AuthClassManageIndexRoute
  '/home': typeof AuthHomeIndexRoute
  '/mysubmit': typeof AuthMysubmitIndexRoute
  '/student-manage': typeof AuthStudentManageIndexRoute
  '/studentdashboard': typeof AuthStudentdashboardIndexRoute
  '/submitlab': typeof AuthSubmitlabIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/forgot-pass': typeof PublicForgotPassIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/test': typeof PublicTestIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/about/': typeof AuthAboutIndexRoute
  '/_auth/assignment-manage/': typeof AuthAssignmentManageIndexRoute
  '/_auth/assignmentlist/': typeof AuthAssignmentlistIndexRoute
  '/_auth/class-manage/': typeof AuthClassManageIndexRoute
  '/_auth/home/': typeof AuthHomeIndexRoute
  '/_auth/mysubmit/': typeof AuthMysubmitIndexRoute
  '/_auth/student-manage/': typeof AuthStudentManageIndexRoute
  '/_auth/studentdashboard/': typeof AuthStudentdashboardIndexRoute
  '/_auth/submitlab/': typeof AuthSubmitlabIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_public/forgot-pass/': typeof PublicForgotPassIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_public/test/': typeof PublicTestIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/assignment-manage'
    | '/assignmentlist'
    | '/class-manage'
    | '/home'
    | '/mysubmit'
    | '/student-manage'
    | '/studentdashboard'
    | '/submitlab'
    | '/users'
    | '/forgot-pass'
    | '/login'
    | '/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/assignment-manage'
    | '/assignmentlist'
    | '/class-manage'
    | '/home'
    | '/mysubmit'
    | '/student-manage'
    | '/studentdashboard'
    | '/submitlab'
    | '/users'
    | '/forgot-pass'
    | '/login'
    | '/test'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_public'
    | '/_auth/about/'
    | '/_auth/assignment-manage/'
    | '/_auth/assignmentlist/'
    | '/_auth/class-manage/'
    | '/_auth/home/'
    | '/_auth/mysubmit/'
    | '/_auth/student-manage/'
    | '/_auth/studentdashboard/'
    | '/_auth/submitlab/'
    | '/_auth/users/'
    | '/_public/forgot-pass/'
    | '/_public/login/'
    | '/_public/test/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_public"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/about/",
        "/_auth/assignment-manage/",
        "/_auth/assignmentlist/",
        "/_auth/class-manage/",
        "/_auth/home/",
        "/_auth/mysubmit/",
        "/_auth/student-manage/",
        "/_auth/studentdashboard/",
        "/_auth/submitlab/",
        "/_auth/users/"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/forgot-pass/",
        "/_public/login/",
        "/_public/test/"
      ]
    },
    "/_auth/about/": {
      "filePath": "_auth/about/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/assignment-manage/": {
      "filePath": "_auth/assignment-manage/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/assignmentlist/": {
      "filePath": "_auth/assignmentlist/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/class-manage/": {
      "filePath": "_auth/class-manage/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/home/": {
      "filePath": "_auth/home/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/mysubmit/": {
      "filePath": "_auth/mysubmit/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/student-manage/": {
      "filePath": "_auth/student-manage/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/studentdashboard/": {
      "filePath": "_auth/studentdashboard/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/submitlab/": {
      "filePath": "_auth/submitlab/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/users/": {
      "filePath": "_auth/users/index.tsx",
      "parent": "/_auth"
    },
    "/_public/forgot-pass/": {
      "filePath": "_public/forgot-pass/index.tsx",
      "parent": "/_public"
    },
    "/_public/login/": {
      "filePath": "_public/login/index.tsx",
      "parent": "/_public"
    },
    "/_public/test/": {
      "filePath": "_public/test/index.tsx",
      "parent": "/_public"
    }
  }
}
ROUTE_MANIFEST_END */
