#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get the current branch name
branch=$(git rev-parse --abbrev-ref HEAD)

# Only add branch name if it's not main/master and not a merge commit
if [[ "$branch" != "main" && "$branch" != "master" && "$branch" != "HEAD" ]] && [ -z "$2" ]; then
  # Extract ticket number or feature name from branch name
  if [[ $branch =~ ^(feature|bugfix|hotfix|chore)/(.+) ]]; then
    prefix="${BASH_REMATCH[1]}"
    name="${BASH_REMATCH[2]}"
    
    # Check if commit message already has the branch info
    if ! grep -q "($name)" "$1"; then
      sed -i.bak -e "1s/^/($name) /" "$1"
    fi
  fi
fi 